### ISSUE TITLE
Alright uhh

### ISSUE THREAD

**Issue by MatthewKarami** [MatthewKarami/2D_Platformer#1]
I made a commit and pushed it using `git commit -a` and then `git push`. It didn't upload all my files though and idk what's going on.

**Comment by theemathas** [comment]
Whatever wasn't uploaded must have matched whatever was in [gitignore](https://github.com/MatthewKarami/2D_Platformer/blob/master/.gitignore). If that's the case, it's supposed to not be uploaded.

**Comment by MatthewKarami** [comment]
@theemathas Ok thanks that must be it.

**Comment by Spyispie120** [comment]
Just saw a new commit 15minutes ago, I think it was just slow to update.
